#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.

DIR=`dirname $0`
. ${DIR}/pgsql_profile || exit 1

analyze_table() {
	TABLENAME=$1
${PSQL} << __EOF__
	ANALYZE ${TABLENAME};
__EOF__
}

USE_TABLESPACES=0
WORKLOAD="H"
while getopts "l:Rt" OPT; do
	case ${OPT} in
	l)
		PORT=${OPTARG}
		;;
	R)
		WORKLOAD="R"
		;;
	t)
		USE_TABLESPACES=1
		;;
	esac
done

if [ ! "x${PORT}" = "x" ]; then
	PORTARG="-p ${PORT}"
fi

if [ -z ${DBNAME} ]; then
	echo "DBNAME not defined."
	exit 1
fi

PSQL="psql -v ON_ERROR_STOP=1 -X -p ${DBPORT} -d ${SID}"

if [ ${USE_TABLESPACES} -eq 1 ];then
	TS_PK_LINEORDER_DIR="${TSDIR}/pk_lineorder/ts"
	TS_PK_SUPPLIER_DIR="${TSDIR}/pk_supplier/ts"
	TS_PK_PART_DIR="${TSDIR}/pk_part/ts"
	TS_PK_CUSTOMER_DIR="${TSDIR}/pk_customer/ts"
	TS_PK_DATE_DIR="${TSDIR}/pk_date/ts"

	mkdir -p ${TS_PK_LINEORDER_DIR}
	mkdir -p ${TS_PK_SUPPLIER_DIR}
	mkdir -p ${TS_PK_PART_DIR}
	mkdir -p ${TS_PK_CUSTOMER_DIR}
	mkdir -p ${TS_PK_ORDER_DIR}

	TS_PK_SUPPLIER="TABLESPACE dbt3_pk_supplier"
	TS_PK_PART="TABLESPACE dbt3_pk_part"
	TS_PK_CUSTOMER="TABLESPACE dbt3_pk_customer"
	TS_PK_ORDERS="TABLESPACE dbt3_pk_orders"
	TS_PK_DATE="TABLESPACE dbt3_pk_date"

	${PSQL} -c "CREATE ${TS_PK_LINEORDER} LOCATION '${TS_PK_LINEORDER_DIR}'";
	${PSQL} -c "CREATE ${TS_PK_PART} LOCATION '${TS_PK_PART_DIR}'";
	${PSQL} -c "CREATE ${TS_PK_SUPPLIER} LOCATION '${TS_PK_SUPPLIER_DIR}'";
	${PSQL} -c "CREATE ${TS_PK_CUSTOMER} LOCATION '${TS_PK_CUSTOMER_DIR}'";
	${PSQL} -c "CREATE ${TS_PK_DATE} LOCATION '${TS_PK_DATE_DIR}'";

	TS_PK_LINEORDER="USING INDEX ${TS_PK_LINEORDER}"
	TS_PK_PART="USING INDEX ${TS_PK_PART}"
	TS_PK_SUPPLIER="USING INDEX ${TS_PK_SUPPLIER}"
	TS_PK_CUSTOMER="USING INDEX ${TS_PK_CUSTOMER}"
	TS_PK_DATE="USING INDEX ${TS_PK_DATE}"
fi

${PSQL} -c "
ALTER TABLE lineorder
ADD CONSTRAINT pk_lineorder
PRIMARY KEY (lo_orderkey, lo_linenumber) ${TS_PK_SUPPLIER};
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON lineorder (lo_quantity, lo_discount);
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON lineorder (lo_partkey);
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON lineorder (lo_suppkey);
" || exit 1 &

${PSQL} -c "
ALTER TABLE supplier
ADD CONSTRAINT pk_supplier PRIMARY KEY (s_suppkey) ${TS_PK_SUPPLIER};
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON supplier (s_region);
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON supplier (s_nation);
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON supplier (s_city);
" || exit 1 &

${PSQL} -c "
ALTER TABLE part
ADD CONSTRAINT pk_part PRIMARY KEY (p_partkey) ${TS_PK_PART};
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON part (p_brand1);
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON part (p_category);
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON part (p_mfgr);
" || exit 1 &

${PSQL} -c "
ALTER TABLE customer
ADD CONSTRAINT pk_customer PRIMARY KEY (c_custkey) ${TS_PK_CUSTOMER};
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON customer (c_region);
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON customer (c_city);
" || exit 1 &

${PSQL} -c "
ALTER TABLE date
ADD CONSTRAINT pk_date PRIMARY KEY (d_datekey) ${TS_PK_DATE};
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON date (d_year, d_weeknuminyear);
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON date (d_yearmonthnum);
" || exit 1 &

${PSQL} -c "
CREATE INDEX ON date (d_yearmonth);
" || exit 1 &

wait

echo "Updating optimizer statistics..."
${PSQL} -c "
analyze lineorder;
analyze part;
analyze supplier;
analyze customer;
analyze date;
" || exit 1;

exit 0
