#!/bin/bash
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2003-2006 Open Source Development Labs, Inc.
#               2003-2006 Jenny Zhang
#               2004-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
set -x
DIR=`dirname $0`
. ${DIR}/../dbt3_profile || exit 1

SRCDIR=${DBT3_HOME}

ANALYZE=
USE_OPROFILE=0
USE_LINUXPERF=0
NO_REFRESH=0

# process the command line parameters
while getopts "ef:l:p:o:s:t:yYz" opt; do
	case $opt in
		e) ANALYZE="EXPLAIN ANALYZE"
			;;
		f) SCALE_FACTOR=$OPTARG
			;;
		l) DBPORT=$OPTARG
			;;
		o) OUTPUT_DIR=$OPTARG
			RESULTSDIR="${OUTPUT_DIR}/results"
			mkdir -p ${RESULTSDIR}
			;;
		p)
			PARAMETERS="${POWER_PARAMETERS} $OPTARG"
			PARAMETERS_ARG="-p \"${POWER_PARAMETERS} $OPTARG\""
			;;
		s) SEED_FILE=$OPTARG
			;;
		y) USE_OPROFILE=1
			;;
		Y) USE_LINUXPERF=1
			;;
		z) NO_REFRESH=1
			;;
		?) echo "Usage: $0 -f <SCALE_FACTOR> [-e -p <db_params> -t <tag> -y]"
			exit ;;
		esac
done

RUNDIR=$OUTPUT_DIR/run
mkdir -p $RUNDIR

DBSCRIPTDIR=${SRCDIR}/scripts/pgsql
DBSTATS="${DBSCRIPTDIR}/db_stats.sh"

PSQL="psql -v ON_ERROR_STOP=1 -X -p ${DBPORT} -d ${SID} -e"

# Get the EXPLAIN plans for only the SELECT statements.
PLANDIR=$OUTPUT_DIR/db/plans
mkdir -p $PLANDIR

for Q in q1_1 q1_2 q1_3 q2_1 q2_2 q2_3 q3_1 q3_2 q3_3 q3_4 q4_1 q4_2 q4_3; do
	SQL=`cat ${DSS_QUERY}/${Q}.sql`
	${PSQL} << __EOF__ > ${PLANDIR}/${Q}.txt
EXPLAIN ${SQL}
__EOF__
done

$DBSCRIPTDIR/dbt3-pgsql-stop-db || exit 1
$DBSCRIPTDIR/dbt3-pgsql-start-db -o ${OUTPUT_DIR} ${PARAMETERS_ARG} || exit 1

# Start collecting system statistics.
$SRCDIR/scripts/dbt3-sysstats --outdir $OUTPUT_DIR --sample 60 || exit 1

# Collect database statistics
${DBSTATS} ${OUTPUT_DIR} ${DBPORT} &

# Clear the read profile counters.
if [ -f /proc/profile ]; then
	clearprof
fi

# Clear the oprofile counters.
if [ $USE_OPROFILE -eq 1 ]; then
	clearoprof
fi

record_start "PERF${TAG}.POWER" || exit 1

# Execute the queries.
for Q in q1_1 q1_2 q1_3 q2_1 q2_2 q2_3 q3_1 q3_2 q3_3 q3_4 q4_1 q4_2 q4_3; do
	SQL=`cat ${DSS_QUERY}/${Q}.sql`
	TASKNAME="PERF.POWER.${Q}"
	QDIR="${OUTPUT_DIR}/${Q}"
	mkdir -p ${QDIR}

	# Start collecting system statistics.
	${SRCDIR}/scripts/dbt3-sysstats --outdir ${QDIR} --sample 60

	# Collect database statistics
	${DBSTATS} ${QDIR} ${DBPORT}

	${PSQL} << __EOF__ > ${OUTPUT_DIR}/results/${Q}.txt
${ANALYZE}
${SQL}
__EOF__

	# Stop collecting system statistics.
	read SARPID < ${QDIR}/sar.pid
	kill ${SARPID}
	read PIDSTATPID < ${QDIR}/pidstat.pid
	kill ${PIDSTATPID}
	read DBSTATSPID < ${QDIR}/db_stats.pid
	kill ${DBSTATSPID}
done > /dev/null 2>&1

record_end ""PERF${TAG}.POWER"" || exit 1
e_time_power=`date +%s`
echo "`date`: Power Test completed."
#let "diff_time=$e_time_power-$s_time_power"
#echo "Elapsed time for Power Test : $diff_time seconds"

$DBSCRIPTDIR/dbt3-pgsql-stop-db || exit 1

if [ -f /proc/profile ]; then
	profname="Power_Test"
	getprof
fi

if [ $USE_OPROFILE -eq 1 ]; then
	profname="Power_Test"
	getoprof
fi

if [ ${USE_LINUXPERF} -eq 1 ]; then
	perf_collect ${OUTPUT_DIR}/perf
fi

exit 0
