#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

if [ "x${PGDATABASE}" = "x" ]; then
	echo "PGDATABASE not defined."
	exit 1
fi

PSQL="psql -X -v ON_ERROR_STOP=1"

${PSQL} -c "DROP TABLE IF EXISTS customer;"
${PSQL} -c "DROP TABLE IF EXISTS date;"
${PSQL} -c "DROP TABLE IF EXISTS lineorder;"
${PSQL} -c "DROP TABLE IF EXISTS part;"
${PSQL} -c "DROP TABLE IF EXISTS supplier;"
${PSQL} -c "DROP TABLE IF EXISTS time_statistics;"
${PSQL} -c "DROP SEQUENCE IF EXISTS dataset;"
