#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

load_table()
{
	table=${1}
	file=${table}.tbl

	${PSQL} << __EOF__
COPY ${table} FROM '${DSS_PATH}/${file}' USING DELIMITERS '|';
__EOF__
}

customer()
{
	load_table customer

	${PSQL} -c "
ALTER TABLE customer
ADD CONSTRAINT pk_customer PRIMARY KEY (c_custkey);" &
	${PSQL} -c "
CREATE INDEX i_customer_region_custkey ON customer (c_region, c_custkey);" &
	${PSQL} -c "
CREATE INDEX i_customer_nation_custkey ON customer (c_nation, c_custkey);" &
	${PSQL} -c "
CREATE INDEX i_customer_city_custkey ON customer (c_city, c_custkey);" &

	wait

	${PSQL} -c "ANALYZE customer;"
}

datet()
{
	load_table date

	${PSQL} -c "
ALTER TABLE date
ADD CONSTRAINT pk_date PRIMARY KEY (d_datekey);" &
	${PSQL} -c "
CREATE INDEX i_date_year_datekey ON date (d_year, d_datekey);" &
	${PSQL} -c "
CREATE INDEX i_date_yearmonthnum_datekey
ON date (d_yearmonthnum, d_datekey);" &
	${PSQL} -c "
CREATE INDEX i_date_yearmonth_datekey ON date (d_yearmonth, d_datekey);" &

	wait

	${PSQL} -c "ANALYZE date;"
}

lineorder()
{
	load_table lineorder

	${PSQL} -c "
ALTER TABLE lineorder
ADD CONSTRAINT pk_lineorder
PRIMARY KEY (lo_orderkey, lo_linenumber);" &
	${PSQL} -c "
CREATE INDEX i_lineorder_discount_quantity
ON lineorder (lo_discount, lo_quantity);" &
	${PSQL} -c "
CREATE INDEX i_lineorder_orderdate ON lineorder (lo_orderdate);" &
	${PSQL} -c "
CREATE INDEX i_lineorder_partkey ON lineorder (lo_partkey);" &
	${PSQL} -c "
CREATE INDEX i_lineorder_custkey ON lineorder (lo_custkey);" &
	${PSQL} -c "
CREATE INDEX i_supplier_suppkey ON lineorder (lo_suppkey);" &

	wait

	${PSQL} -c "ANALYZE lineorder;"
}

part()
{
	load_table part

	${PSQL} -c "
ALTER TABLE part
ADD CONSTRAINT pk_part PRIMARY KEY (p_partkey);" &
	${PSQL} -c "
CREATE INDEX i_part_category_partkey ON part (p_category, p_partkey);" &
	${PSQL} -c "
CREATE INDEX i_part_brand1_partkey ON part (p_brand1, p_partkey);" &
	${PSQL} -c "
CREATE INDEX i_part_mfgr_partkey ON part (p_mfgr, p_partkey);" &

	wait

	${PSQL} -c "ANALYZE part;"
}

supplier()
{
	load_table supplier

	${PSQL} -c "
ALTER TABLE supplier
ADD CONSTRAINT pk_supplier PRIMARY KEY (s_suppkey);" &
	${PSQL} -c "
CREATE INDEX i_supplier_region_suppkey ON supplier (s_region, s_suppkey);" &
	${PSQL} -c "
CREATE INDEX i_supplier_nation_suppkey ON supplier (s_nation, s_suppkey);" &
	${PSQL} -c "
CREATE INDEX i_supplier_city_suppkey ON supplier (s_city, s_suppkey);" &

	wait

	${PSQL} -c "ANALYZE supplier;"
}

USE_TABLESPACES=0
while getopts "t" OPT; do
	case ${OPT} in
	t)
		USE_TABLESPACES=1
		;;
	esac
done

PSQL="psql -v ON_ERROR_STOP=1 -X"

lineorder &
part &
supplier &
customer &
datet &

wait
