#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see the file LICENSE, included in this package, for details.
#
# Copyright (C) 2002-2008 Open Source Development Labs, Inc.
#               2002-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.

create_table() {
	SQL=${1}

	${PSQL} << __EOF__
${SQL};
__EOF__
	return $?
}

USE_TABLESPACES=0
while getopts "t" OPT; do
	case ${OPT} in
	t)
		USE_TABLESPACES=1
		;;
	esac
done

PSQL="psql -v ON_ERROR_STOP=1 -X -A -t"

if [ ${USE_TABLESPACES} -eq 1 ]; then
	TS_LINEORDER_DIR="${TSDIR}/lineorder/ts"
	TS_PART_DIR="${TSDIR}/part/ts"
	TS_SUPPLIER_DIR="${TSDIR}/supplier/ts"
	TS_CUSTOMER_DIR="${TSDIR}/customer/ts"
	TS_DATE_DIR="${TSDIR}/date/ts"

	mkdir -p ${TS_LINEORDER_DIR}
	mkdir -p ${TS_PART_DIR}
	mkdir -p ${TS_SUPPLIER_DIR}
	mkdir -p ${TS_CUSTOMER_DIR}
	mkdir -p ${TS_DATE_DIR}

	LINEORDER_TABLESPACE="TABLESPACE dbt6_lineorder"
	PART_TABLESPACE="TABLESPACE dbt6_part"
	SUPPLIER_TABLESPACE="TABLESPACE dbt6_supplier"
	CUSTOMER_TABLESPACE="TABLESPACE dbt6_customer"
	DATE_TABLESPACE="TABLESPACE dbt6_date"

	${PSQL} -c "CREATE ${LINEORDER_TABLESPACE} LOCATION '${TS_LINEORDER_DIR}';"
	${PSQL} -c "CREATE ${PART_TABLESPACE} LOCATION '${TS_PART_DIR}';"
	${PSQL} -c "CREATE ${SUPPLIER_TABLESPACE} LOCATION '${TS_SUPPLIER_DIR}';"
	${PSQL} -c "CREATE ${CUSTOMER_TABLESPACE} LOCATION '${TS_CUSTOMER_DIR}';"
	${PSQL} -c "CREATE ${DATE_TABLESPACE} LOCATION '${TS_DATE_DIR}';"
fi

create_table "
CREATE TABLE lineorder (
	lo_orderkey INTEGER,
	lo_linenumber INTEGER,
	lo_custkey INTEGER,
	lo_partkey INTEGER,
	lo_suppkey INTEGER,
	lo_orderdate DATE,
	lo_orderpriority CHAR(15),
	lo_shippriority INTEGER,
	lo_quantity REAL,
	lo_extendedprice REAL,
	lo_ordtotalprice REAL,
	lo_discount REAL,
	lo_revenue REAL,
	lo_supplycost REAL,
	lo_tax REAL,
	lo_commitdate DATE,
	lo_shipmode CHAR(10)
	${LINEORDER_TABLESPACE});" || exit 1

create_table "
CREATE TABLE part (
	p_partkey INTEGER,
	p_name VARCHAR(22),
	p_mfgr CHAR(6),
	p_category CHAR(7),
	p_brand1 CHAR(9),
	p_color VARCHAR(11),
	p_type VARCHAR(25),
	p_size INTEGER,
	p_container CHAR(10)
	${PART_TABLESPACE});" || exit 1

create_table "
CREATE TABLE supplier (
	s_suppkey INTEGER,
	s_name CHAR(50),
	s_address VARCHAR(25),
	s_city CHAR(10),
	s_nation CHAR(15),
	s_region CHAR(12),
	s_phone CHAR(15)
	${SUPPLIER_TABLESPACE});" || exit 1

create_table "
CREATE TABLE customer (
	c_custkey BIGINT,
	c_name VARCHAR(25),
	c_address VARCHAR(25),
	c_city CHAR(10),
	c_nation CHAR(15),
	c_region CHAR(12),
	c_phone CHAR(15),
	c_mktsegment CHAR(10)
	${CUSTOMER_TABLESPACE});" || exit 1

create_table "
CREATE TABLE date (
	d_datekey DATE,
	d_date CHAR(18),
	d_dayofweek CHAR(9),
	d_month CHAR(9),
	d_year INTEGER,
	d_yearmonthnum INTEGER,
	d_yearmonth CHAR(7),
	d_daynuminweek INTEGER,
	d_daynuminmonth INTEGER,
	d_daynuminyear INTEGER,
	d_monthnuminyear INTEGER,
	d_weeknuminyear INTEGER,
	d_sellingseason VARCHAR(12),
	d_lastdayinweekfl BOOLEAN,
	d_lastdayinmonthfl BOOLEAN,
	d_holidayfl BOOLEAN,
	d_weekdayfl BOOLEAN
	${DATE_TABLESPACE});" || exit 1

create_table "
CREATE TABLE time_statistics (
	task_name VARCHAR(40),
	s_time TIMESTAMP,
	e_time TIMESTAMP);" || exit 1
