#!/bin/sh
#
# This file is released under the terms of the Artistic License.
# Please see # the file LICENSE, included in this package, for details.
#
# Copyright (C) 2004      Open Source Development Labs, Inc.
#               2004       Jenny Zhang
#               2004-2014 Mark Wong
#               2014      2ndQuadrant, Ltd.
#

NO_REFRESH=0
while getopts "a:ef:n:o:s:Yz" opt; do
	case $opt in
	a) DATABASE=$OPTARG
		;;
	e) EXPLAIN_ARG="-y"
		;;
	f) scale_factor=$OPTARG
		;;
	n) num_stream=$OPTARG
		;;
	o) OUTPUT_DIR=$OPTARG
		;;
	s) SEED_FILE=$OPTARG
		;;
	Y) LINUXPERF_ARG="-Y"
		;;
	z) NO_REFRESH=1
		;;
	\?) exit 1
		;;
	esac
done

if [ "x$DATABASE" = "x" ]; then
	echo "Specify database management system with -a flag"
	exit 1
fi

RUNDIR=$OUTPUT_DIR/run

# Start each stream.
i=1
while [ $i -le $num_stream ] 
do
	dbt6-throughput-stream \
			-f ${scale_factor} \
			-t ${i} \
			${EXPLAIN_ARG} \
			${LINUXPERF_ARG} \
			-o ${OUTPUT_DIR} \
			-s ${SEED_FILE} > ${RUNDIR}/thruput_qs${i} 2>&1 &
	
	i=$(( $i + 1 ))
done

wait
